### Demo Scikit-learn Program

In [88]:
# Step 1: Import the tools you need
from sklearn.datasets import load_iris  # Built-in dataset
from sklearn.model_selection import train_test_split  # Split data
from sklearn.neighbors import KNeighborsClassifier  # A simple model
from sklearn.metrics import accuracy_score  # Check how good the model is

# Step 2: Load a dataset (like gathering ingredients)
iris = load_iris()
X = iris.data  # Features (measurements of flowers)
y = iris.target  # Labels (types of flowers: 0, 1, or 2)

# Step 3: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Choose and train a model
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)  # "fit" = train the model

# Step 5: Make predictions
predictions = model.predict(X_test)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, predictions)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 100.00%


### Understanding Dataset

In [11]:
import numpy as np

# Explore the data
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("\nShape of X:", iris.data.shape)  # (150 samples, 4 features)
print("Shape of y:", iris.target.shape)  # (150 samples,)

# Look at first 5 rows
print("\nFirst 5 samples (features):")
print(iris.data[:5])

print("\nFirst 5 labels:")
print(iris.target[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Shape of X: (150, 4)
Shape of y: (150,)

First 5 samples (features):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 labels:
[0 0 0 0 0]


### Train-Test-Split

In [14]:
iris = load_iris()
X, y = iris.data, iris.target

# Split: 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2,      # 20% for testing
    random_state=42     # For reproducibility (same split every time)
)

print("Training samples:", len(X_train))  # 120
print("Test samples:", len(X_test))       # 30

Training samples: 120
Test samples: 30


In [36]:
# Exercise 1

from sklearn.datasets import load_digits

digits=load_digits()
X = digits.data
y = digits.target

# 2. Print the shape of X and y
print("X shape", X.shape)
print("y shape", y.shape)

# 3. Print the first sample's features and label
print(X[0])
print(y[0])

# 4. How many samples and features are there?
print("Samples; ", X.shape[0])
print("Features: ", X.shape[1])

X shape (1797, 64)
y shape (1797,)
[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
0
Samples;  1797
Features:  64


In [66]:
# Exercise 2

X, y = digits.data, digits.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

print(X_train[:3])
print(X_test[:3])
print(y_train[:3])
print(y_test[:3])

(1257, 64)
(540, 64)
(1257,)
(540,)
[[ 0.  0.  1. 13. 16. 10.  0.  0.  0.  1. 13. 15.  8. 16.  3.  0.  0.  8.
  15.  3.  4. 15.  0.  0.  0.  1.  3.  0. 12.  8.  0.  0.  0.  0.  0.  4.
  14.  1.  0.  0.  0.  0.  0. 11.  8.  0.  4.  0.  0.  0.  1. 16.  8. 13.
   9.  0.  0.  0.  0. 14. 16. 11.  0.  0.]
 [ 0.  0. 10. 10. 12.  7.  0.  0.  0.  0. 15. 13.  5. 12.  5.  0.  0.  4.
  13.  4.  0.  2.  8.  0.  0.  8.  4.  0.  0.  3.  8.  0.  0.  8.  4.  0.
   0.  7.  5.  0.  0.  6.  6.  0.  0. 11.  2.  0.  0.  1. 13.  3.  3. 12.
   0.  0.  0.  0.  7. 15. 16.  7.  0.  0.]
 [ 0.  0.  2. 11. 13.  5.  0.  0.  0.  1. 14.  9.  8. 14.  0.  0.  0.  6.
  13.  1.  2. 16.  2.  0.  0.  7.  7.  0.  0. 12.  5.  0.  0.  7.  9.  0.
   0.  3.  9.  0.  0.  2. 12.  0.  0.  4. 11.  0.  0.  0. 12.  6.  4. 14.
   7.  0.  0.  0.  3. 13. 16.  9.  0.  0.]]
[[ 0.  0.  0. 10. 12.  8.  1.  0.  0.  0.  5. 16. 16. 16.  0.  0.  0.  0.
  10. 16. 16.  9.  0.  0.  0.  2. 15. 16. 13.  2.  0.  0.  0.  4. 16. 16.
   8.  0.  0.  0.  0

In [89]:
# Exercise 3

from sklearn.neighbors import KNeighborsClassifier
iris = load_iris()

X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=40)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)
acc = accuracy_score(y_test, predictions)

print("Accuracy:", acc)

Accuracy: 1.0
