In [32]:
# Broadcasting - perform array operations directy on the array(can be of different shapes)
# Simple Row Broadcasting

import numpy as np

arr = np.array([10, 20, 30, 40])
result = arr + 5
print("Array + scalar:", result)  
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) # 3 column, 3 row
row_vector = np.array([10, 20, 30])
result = arr_2d + row_vector

print("\n2D array:\n", arr_2d)
print("\nRow vector:", row_vector)
print("\nBroadcasted result:\n", result)

Array + scalar: [15 25 35 45]

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row vector: [10 20 30]

Broadcasted result:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [17]:
# Simple Column broadcasting

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

col_vector = np.array([[10],
                       [20],
                       [30]]) # 3 column, 1 row
result = arr_2d + col_vector
print("2D array:\n", arr_2d)
print("\nColumn vector:\n", col_vector)
print("\nBroadcasted result:\n", result)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Column vector:
 [[10]
 [20]
 [30]]

Broadcasted result:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]


In [18]:
# Rule: Arrays are compatible when dimensions match OR one is 1

# Example 1: Compatible
a = np.array([[1, 2, 3]]) #shape (1, 3)
b = np.array([[10],
              [20],
              [30]]) #shape (3, 1)
result = a + b
print("Shape a:", a.shape)
print("Shape b:", b.shape)
print("Result shape:", result.shape)  #(3, 3)
print("Result:\n", result)

# Example 2: What happens step-by-step
print("a (1,3) is stretched to (3,3):")
print(np.broadcast_to(a, (3, 3)))
print("\nb (3,1) is stretched to (3,3):")
print(np.broadcast_to(b, (3, 3)))

Shape a: (1, 3)
Shape b: (3, 1)
Result shape: (3, 3)
Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
a (1,3) is stretched to (3,3):
[[1 2 3]
 [1 2 3]
 [1 2 3]]

b (3,1) is stretched to (3,3):
[[10 10 10]
 [20 20 20]
 [30 30 30]]


In [21]:
# Vectoization - Instead of looping an array, numpy does it without regular python loop
import time

data = np.arange(1000000)
start = time.time()
result_loop = []
for x in data:
    result_loop.append(x * 2 + 5)
time_loop = time.time() - start

start = time.time()
result_vec = data * 2 + 5
time_vec = time.time() - start

print(f"Loop time: {time_loop:.4f} seconds")
print(f"Vectorized time: {time_vec:.4f} seconds")
print(f"Speedup: {time_loop/time_vec:.1f}x faster!")

Loop time: 0.2045 seconds
Vectorized time: 0.0065 seconds
Speedup: 31.4x faster!


In [31]:
X = np.random.rand(100) * 10  # Random values 0-10
w = 2.5
b = 10
predictions = w * X + b # Vectorized

print("First 10 inputs:", X[:10])
print("First 10 predictions:", predictions[:10])
print("\nShape of X:", X.shape)
print("Shape of predictions:", predictions.shape)

First 10 inputs: [5.73448453 3.33988967 5.61888169 8.08886952 3.74968331 6.47046684
 3.11831247 1.54421521 5.49991599 6.92412457]
First 10 predictions: [24.33621132 18.34972418 24.04720422 30.22217381 19.37420827 26.17616709
 17.79578118 13.86053803 23.74978997 27.31031143]

Shape of X: (100,)
Shape of predictions: (100,)


In [34]:
# Example: finding MSE
# True values
y_true = np.array([100, 150, 200, 250, 300])

# Predicted values
y_pred = np.array([110, 140, 210, 240, 295])

# Mean Squared Error (MSE) - fully vectorized!
squared_errors = (y_true - y_pred) ** 2
mse = squared_errors.mean()

print("True values:", y_true)
print("Predictions:", y_pred)
print("Squared errors:", squared_errors)
print("MSE:", mse)

True values: [100 150 200 250 300]
Predictions: [110 140 210 240 295]
Squared errors: [100 100 100 100  25]
MSE: 85.0


In [55]:
# Exercise 1

arr1 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# 1. Add 100 to all elements
add_100 = arr1+100
print(add_100)

# 2. Multiply each row by [1, 2, 3, 4] (row broadcasting)
row = np.array([1, 2, 3, 4])
row_broadcasting = arr1 + row
print(row_broadcasting)

# 3. Add [10, 20, 30] to each column (column broadcasting - reshape to (3,1)!)
column = np.array([[10], [20], [30]])
# column = np.array([10, 20, 30]).reshape(3,1)
col_broadcasting = arr1 + column
print(col_broadcasting)

[[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
[[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


In [58]:
# Exercise 2

celsius = np.array([0, 10, 20, 30, 40, 100])

# Convert ALL to Fahrenheit using: F = C * 9/5 + 32
fahrenheit = (celsius * 9/5) + 32
print(fahrenheit)

[ 32.  50.  68.  86. 104. 212.]


In [70]:
# Exercise 3

a = np.ones((4, 1))
b = np.ones((1, 5))

print(a)
print(b)
print(a+b)

[[1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1. 1. 1.]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [89]:
# Exercise 4

X = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0],
              [10.0, 11.0, 12.0],
              [13.0, 14.0, 15.0]])

col_mean = X.mean(axis=0)
col_std = X.std(axis=0)

standardized = (X - col_mean) / col_std
print(standardized)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
