In [3]:
# Array slicing 

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Slicing syntax: arr[start:stop:step]
print("First 3:", arr[0:3])      # [10 20 30]
print("From index 2 to 5:", arr[2:5])  # [30 40 50]
print("Every other element:", arr[::2]) # [10 30 50 70]
print("First 4:", arr[:4])       # [10 20 30 40] (start defaults to 0)
print("Last 3:", arr[-3:])       # [50 60 70]
print("Reverse:", arr[::-1])     # [70 60 50 40 30 20 10]

First 3: [10 20 30]
From index 2 to 5: [30 40 50]
Every other element: [10 30 50 70]
First 4: [10 20 30 40]
Last 3: [50 60 70]
Reverse: [70 60 50 40 30 20 10]


In [6]:
# Array modification

arr = np.array([10, 20, 30, 40, 50])

# Modify single element
arr[0] = 100
print("After modifying first:", arr)  # [100  20  30  40  50]

# Modify multiple elements using slicing
arr[1:4] = 999
print("After slice modification:", arr)  # [100 999 999 999  50]

# Modify using another array
arr[1:4] = np.array([200, 300, 400])
print("After array modification:", arr)  # [100 200 300 400  50]

After modifying first: [100  20  30  40  50]
After slice modification: [100 999 999 999  50]
After array modification: [100 200 300 400  50]


In [9]:
# Basic arithmetic operations

arr = np.array([1, 2, 3, 4, 5])

# Element-wise operations
print("Add 10:", arr + 10)        # [11 12 13 14 15]
print("Multiply by 2:", arr * 2)  # [ 2  4  6  8 10]
print("Square:", arr ** 2)        # [ 1  4  9 16 25]
print("Divide by 2:", arr / 2)    # [0.5 1.  1.5 2.  2.5]

Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [13]:
# Array to arrya operations

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

# Element-wise operations between arrays
# array must have same shape
print("Addition:", arr1 + arr2)       # [11 22 33 44]
print("Multiplication:", arr1 * arr2) # [10 40 90 160]
print("Subtraction:", arr1 - arr2)    # [-9 -18 -27 -36]

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
Subtraction: [ -9 -18 -27 -36]


In [16]:
# Feature normalization

# Raw feature values (e.g., house prices in dollars)
prices = np.array([300000, 450000, 200000, 800000, 350000])

# Normalization: scale to 0-1 range
min_price = prices.min()
max_price = prices.max()
normalized = (prices - min_price) / (max_price - min_price)

print("Original:", prices)
print("Normalized:", normalized)

Original: [300000 450000 200000 800000 350000]
Normalized: [0.16666667 0.41666667 0.         1.         0.25      ]


In [20]:
# Exercise 1

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(arr[5])
print(arr[-1])
print(arr[2:6])
print(arr[::3])

30
40
[15 20 25 30]
[ 5 20 35]


In [30]:
# Exercise 2

temps = np.array([72, 68, 75, 70, 73, 69, 71])

temps[0:4] = 80
print(temps)

print(temps[-4:])

print(temps[::-1])

[80 80 80 80 73 69 71]
[80 73 69 71]
[71 69 73 80 80 80 80]


In [50]:
# Exercise 3

scores = np.array([85, 90, 78, 92, 88])

scores+=5
print(scores)

sqr_diffs = (scores-100)
print(sqr_diffs**2)

percent = scores/100
print(percent*100)

[90 95 83 97 93]
[100  25 289   9  49]
[90. 95. 83. 97. 93.]


In [59]:
# Exercise 4

sizes = np.array([1200, 1800, 950, 2400, 1600])

mn = sizes.mean()
sd = sizes.std()
stand = (sizes - mn)/sd

print(mn, sd, stand)
print(stand.mean())

1590.0 502.3942674832188 [-0.77628274  0.4179984  -1.27389989  1.61227954  0.01990469]
-1.0408340855860843e-17
